version: '3.8'

services:
  calculator-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MONGO_DB_NAME=calculator
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    networks:
      - calculator-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=calculator
    volumes:
      - mongodb_data:/data/db
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge

volumes:
  mongodb_data: