apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=        # 'admin' in base64
  mongo-root-password: cGFzc3dvcmQ=    # 'password' in base64
  mongo-db-name: Y2FsY3VsYXRvcg==      # 'calculator' in base64